// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxQTCJgVuu3Fba-PWqIJ3c-Cv5OCOUozc',
    appId: '1:451160567687:android:2a547a1be98e57d192ad22',
    messagingSenderId: '451160567687',
    projectId: 'jnec-eco-trade-fa7f1',
    storageBucket: 'jnec-eco-trade-fa7f1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKgRHDfbWifopzXzzX3DHl2fwVj6C8j10',
    appId: '1:451160567687:ios:1c3ea5451cb1a2d992ad22',
    messagingSenderId: '451160567687',
    projectId: 'jnec-eco-trade-fa7f1',
    storageBucket: 'jnec-eco-trade-fa7f1.firebasestorage.app',
    androidClientId: '451160567687-5brdl9bpveu8tsoj74p2354nbv5atkoa.apps.googleusercontent.com',
    iosClientId: '451160567687-1vrn1hrr8mr6molg4gqlsl4o1f64o4bu.apps.googleusercontent.com',
    iosBundleId: 'com.rabten.jnececotrade',
  );
}
